
# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


loader_version_range=[52,)

# Minecraft

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Mod Properties

mod_name=TheDragon's Blowpipes Mod
mod_id=blowpipemod
mod_license=MIT
mod_version=1.2.0
mod_group_id=net.thedragonskull.blowpipemod
moonlight_version=moonlight-1.21-2.17.37-neoforge
curios_version=9.4.0+1.21.1
mod_authors=TheDragonSkull
mod_description=A mod that adds blowguns and some darts. Three of the darts have been heavily inspired by the darts from the game "Sea of Thieves".


# NeoForge

# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.93
# The Neo version range can use any version of Neo as bounds
neo_version_range=[21.0.0-beta,)