
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"

[[mods]]
modId="blowpipemod"
version="1.2.0"
displayName="TheDragon's Blowpipes Mod"
description='''A mod that adds blowguns and some darts. Three of the darts have been heavily inspired by the darts from the game "Sea of Thieves".'''
logoFile = "logo.png"
authors="TheDragonSkull"

[[dependencies.blowpipemod]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.blowpipemod]]
    modId="minecraft"
    type="required"
    versionRange="1.21.1"
    ordering="NONE"
    side="BOTH"

[[dependencies.blowpipemod]]
    modId="moonlight"
    type="required"
    versionRange="[moonlight-1.21-2.17.37-neoforge,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blowpipemod]]
    modId="curios"
    type="required"
    versionRange="[9.4.0+1.21.1,)"
    ordering="NONE"
    side="BOTH"